import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PayPalWrapper from "@/components/PayPalWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kridha The Master of Virtual World",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <PayPalWrapper>
        {children}
        </PayPalWrapper>
      </body>
    </html>
  );
}
